skip_commits:
  message: /^Merge pull request /

build: false
image: Visual Studio 2019
environment:
  PYTHONIOENCODING: "UTF-8"

  matrix:
    - PYTHON_VERSION: "3.8"
      PYTHON_ARCH: "64"
      CONDA_PY: "38"
      CONDA_INSTALL_LOCN: "C:\\Miniconda38-x64"

install:
  - call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
  - python --version
  - conda config --set always_yes yes
  - conda config --append channels conda-forge
  - conda config --append channels cmutel
  - conda config --append channels konstantinstadler
  - conda config --append channels haasad
  - conda config --append channels pascallesage
  - conda config --append channels romainsacchi
  - conda config --set channel_priority strict
  - conda update -y conda
  - conda install -y numpy pandas bw2io>0.8
  - conda install -y bw2data wurst>=0.3 xarray pycountry pytest pytest-cov coveralls
  - conda install -y prettytable carculator carculator_truck cryptography
  - pip install -e .

test_script:
  - pytest -m "not ecoinvent"
