skip_commits:
  message: /^Merge pull request /

build: false
image: Visual Studio 2019
environment:
  PYTHONIOENCODING: "UTF-8"

  matrix:
    - PYTHON_VERSION: "3.8"
      PYTHON_ARCH: "64"
      CONDA_PY: "38"
      CONDA_INSTALL_LOCN: "C:\\Miniconda38-x64"

install:
  - call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
  - python --version
  - conda config --set always_yes yes
  - conda update -y conda
  - conda install -y -c conda-forge -c cmutel -c romainsacchi -c konstantinstadler numpy pandas bw2io>0.8 bw2data wurst>=0.3 xarray pycountry pytest pytest-cov coveralls prettytable carculator carculator_truck
  - pip install -e .

test_script:
  - pytest -m "not ecoinvent"
